### ISSUE TITLE
API：加上分頁

### ISSUE THREAD

**Issue by hikarunost** [MonospaceTW/monosparta-diving-server#32]
分頁格式：
一頁15筆資料。

以下API需要加上分頁規則
- [x] Show spot search list
- [x] Show spot search with Location and Level
- [x] Show shop search list  
- [x] Show shop search with Location and Level
- [x] Show article list
- [x] Show article category list

**Comment by lukechu1997** [comment]
@hikarunost information not enough

**Comment by hikarunost** [comment]
以下API需要加上分頁規則
- [ ] Show spot search list
- [ ] Show spot search with Location and Level
- [ ] Shop certain spot detail  (comment)
- [ ] Show shop search list  
- [ ] Show shop search with Location and Level
- [ ] Shop certain shop detail  (comment)
- [ ] Spot/Shop/Article keyword search
- [ ] Show article list
- [ ] Show article category list

**Comment by hikarunost** [comment]
@ssiyang @yinmin8610 請先測試一下這是不是你們要的分頁方式
[測試用的文章列表API](http://8e702c06.ngrok.io/DivingBackend/public/api/article)

**Comment by hikarunost** [comment]
@ssiyang @yinmin8610 
我做完所有需要分頁的API了
可以在[API文件](https://divingapi.docs.apiary.io/#)做測試
確認沒問題的在下面幫我打勾，謝謝

- [ ] Show spot search list
- [ ] Show spot search with Location and Level
- [ ] Show shop search list  
- [ ] Show shop search with Location and Level
- [ ] Spot/Shop/Article keyword search
- [ ] Show article list
- [ ] Show article category list

**Comment by hikarunost** [comment]
關鍵字需要分頁嗎?

**Comment by yinmin8610** [comment]
目前不需要
