### ISSUE TITLE
整理真實資料

### ISSUE THREAD

**Issue by jasminesie** [MonospaceTW/monosparta-diving-server#33]
資料項目可以在[表單](https://docs.google.com/spreadsheets/d/1p0u3-xFrxuPSvPnBSRdQN_I58bve-F7GfTQKE7UEVZA/edit#gid=0)查看

- [x] Alice：離島
- [x] Brian：東部
- [x] Jasmine：北部
- [x] Ann：中部
- [x] Luke：南部

截止時間：8/7

**Comment by hikarunost** [comment]
整裡完的潛點和潛店可以在[google地圖](https://drive.google.com/open?id=1cufcbTaUPIbJy3bj14xwmKrIBfni2UaD&usp=sharing)查看

**Comment by hikarunost** [comment]
@ssiyang @yinmin8610 @lukechu1997 @jasminesie @hikarunost 
資料整理成匯入資料庫的格式
-[ ] spots
-[ ] shops
-[ ] articles
