### ISSUE TITLE
儲存文章內容

### ISSUE THREAD

**Issue by hikarunost** [MonospaceTW/monosparta-diving-server#34]
文章內文用HTML存在資料庫

**Comment by lukechu1997** [comment]
postman add articles
node mysql unicode input

**Comment by lukechu1997** [comment]
uploading articles

**Comment by lukechu1997** [comment]
@yinmin8610 @ssiyang @hikarunost 
article import is done, check your apps.
knowledge and license do not exist in the offered json file

**Comment by hikarunost** [comment]
@lukechu1997 
travel分類的文章確認可以抓到，就比賽的要求來說就先這樣子，之後要優化再說。
