### ISSUE TITLE
[test]無限捲動紅寶石

### ISSUE THREAD

**Issue by lukechu1997** [MonospaceTW/monosparta-diving-server#40]
* [ ] 取得設計稿
* [ ] 取得素材
* [x] toggle button -> 無限捲動
* [ ] button size: 1rem
* [ ] for logged in users only

**Comment by lukechu1997** [comment]
@yinmin8610

**Comment by yinmin8610** [comment]
@yinmin8610 @jasminesie @hikarunost @ssiyang I had finished my dirty works, please take a look. Thank you very much!

**Comment by yinmin8610** [comment]
@BlueT  so what the fuck should i do?
TELL MEEEEEEEE!!! 777
