### ISSUE TITLE
Database: table relationship establish

### ISSUE THREAD

**Issue by lukechu1997** [MonospaceTW/monosparta-diving-server#42]
[ERD_V4.pdf](https://app.zenhub.com/files/196555024/630d66a3-4e33-48cd-9ad4-75018a23566a/download)
* [x] define table relationship
* [x] establish model connections

**Comment by lukechu1997** [comment]
@hikarunost @yinmin8610 @ssiyang 
comment finished
POST: https://0d810ac2.ngrok.io/api/comment
body: 
{
	"comment" : "test message",
	"rating" : "4",
	"user_id" : "2",
	"shop_id" : "5" //or "spot_id" : "5"
}

**Comment by hikarunost** [comment]
@lukechu1997 
Checking the API is done! 
I can add comment and check the comment with spot/shop.

 "created_at" and"updated_at" appear twice in the api. (like code below)
Please improve this problem later.

`    "comment": [
        {
            "id": 1025,
            "created_at": "2019-08-08 06:35:19",
            "updated_at": "2019-08-08 06:35:19",
            "comment": "test messageggggggg",
            "rating": 4,
            "user_id": 2,
            "pivot": {
                "spot_id": 3,
                "comment_id": 1025,
                "created_at": "2019-08-08 06:35:19",
                "updated_at": "2019-08-08 06:35:19"
            }
        }
    ]`
