### ISSUE TITLE
API: error handling

### ISSUE THREAD

**Issue by champagne5722** [MonospaceTW/monosparta-diving-server#6]
error code 400, 500

400 Bad Request : The request could not be understood or was missing required parameters.
500 Internal Server Error

**Comment by lukechu1997** [comment]
error code 400, 500

**Comment by lukechu1997** [comment]
@hikarunost  @yinmin8610 @ssiyang 
https://0d810ac2.ngrok.io/api/....
send http request to url above with postman
API document : https://divingapi.docs.apiary.io/#reference/search/spot-search

**Comment by hikarunost** [comment]
評論的那兩隻目前是404是正確的嗎?
