### ISSUE TITLE
資料庫：調整內容

### ISSUE THREAD

**Issue by ssiyang** [MonospaceTW/monosparta-diving-server#60]
前端發現一些潛點/潛店資料可以改進的地方，如下列表，請檢查資料庫內容

潛店圖片網址格式不正確 (無法抓到圖片)
- [x] 北部 :id 2 亞潮潛水
- [x]              3 巡航艦潛水
- [x]               8 橘子鯊潛水
- [x]               11(第1張) 愛潛水全方位潛水中心

- [x] 南部: id 59 墾丁環礁潛水中心
- [x] 64 放呆潛水俱樂部 (第1張)
- [x]  66 潛莊潛水渡假中心 (第2張)

潛店圖片無法顯示
- [x] 北部: id  7 海洋芒果潛水裝備專賣店 (第2~5張)
- [x]   16 潛水易購網 (第2~5張)

- [x] 中部: id  27 台中潛水訓練中心  (第2~3張)

潛店圖片重複
- [x] 中部: id  30 海洋芒果潛水裝備專賣店
- [x]                      32 碧海藍天國際潛水飛行聯盟
- [x]                      34 宇洋水上體育用品店 (1&2張)
- [x]                      35 探險家戶外用品 (2&3張)
- [x]                      37 海蛞蝓技術潛水訓練中心
- [x]                      39 野蠻紮實潛水訓練中心 (1&2張)
- [x]                      42 PADI威鯨潛水訓練中心 (2~4張)
- [x]                      38 廣三SOGO努特生活館 與 35 探險家戶外用品 照片一樣

潛店圖片死圖 
- [x] 中部: id 43 藍灣潛水訓練中心 (第4張)

潛店未放圖 
- [x] 南部: id 墾丁新台北潛水中心 69

潛店網址連結錯誤
- [x] 外島 id 79 小琉球小綠龜潛水 FB網址錯誤 ( 少 http:// )
- [x] 南部 id 51 乖巧鯊潛水渡假村 url 連結已死
- [x] 中部 id 46 Go Diving趣潛水 FB連結為 "一個空白"
- [x] 29  乖巧鯊潛水訓練中心 url 網址錯誤 ( 少 http:// )

潛店名稱錯誤
- [x] 北部 id 15 NEREUS 加上 潛水貨倉

潛店網址 url 需 FB 跳轉
- [x] 北部 id 13 鬥陣潛水教學休閒俱樂部 url 修改為 https://www.joindiving.com.tw/web/Home/Index?key=656715000196
- [x]              11 愛潛水全方位潛水中心 url 修改為 https://www.idiving.com.tw/
- [x]              10 深態潛水訓練中心 url 修改為 https://dive-shop-437.business.site/
- [x]              9 東北角潛水客棧 url 修改為 http://diver228.divers.com.tw/
- [x]              8 橘子鯊潛水 url 修改為 https://www.orange-shark.com.tw/
- [x]              7 海洋芒果潛水裝備專賣店 url 修改為 http://www.ocean-mango.com/

潛店地址重複 (縣市地區)
- [x] 北部: id 1~13 
- [x] 離島 id 77

潛點圖片網址格式不正確 (無法抓到圖片)
- [x] 北部: id 1 野柳(第5張)

潛點圖片重複
- [x] 北部: id 1 野柳(1&2張)

**Comment by hikarunost** [comment]
發現伺服器資料表shops被匯入不完整、沒整理過的資料

**Comment by hikarunost** [comment]
@ssiyang 已把潛店的 99 筆正確資料更新上伺服器的資料表 shops ，請再檢查一次資料是否正確，感恩。

**Comment by hikarunost** [comment]
spot 
id=1，第一章圖片改成　https://live.staticflickr.com/1898/44022365164_a0f3ec6610_n.jpg

**Comment by hikarunost** [comment]
@jasminesie 
北部
重找圖片
潛店id：  2 亞潮潛水 (換掉全部圖片),
    　　 3 巡航艦潛水 (換掉全部圖片),
    　　 7 海洋芒果 (換掉第2~5張),
    　　 8 橘子沙潛水 (換掉全部圖片),
    　　 11 愛潛水 (換掉第1張),
    　　 16 潛水易購網 (換掉第2~5張)

**Comment by hikarunost** [comment]
shop
id = 51
url 改成 http://www.sharkie.com.tw/

**Comment by hikarunost** [comment]
shop
id = 29
url 改成 http://www.7s.com.tw/

**Comment by hikarunost** [comment]
shop
id = 43
img4刪除

**Comment by hikarunost** [comment]
shop
id = 69
img1 新增 https://img.uukt.com.tw/member_upload/6109/720/201709081543200VXF2.jpg
img2 新增 https://img.uukt.com.tw/member_upload/6109/720/20170908154318GyTN9.jpg
img3 新增 https://img.uukt.com.tw/member_upload/6109/720/20170908154320GMORE.jpg

**Comment by hikarunost** [comment]
shop 
id = 30
img2 新增 http://www.ocean-mango.com/wp-content/uploads/2014/10/cropped-P6304182-2.jpg
img3 刪除

**Comment by hikarunost** [comment]
shop
id = 32
img2 新增 https://scontent.frmq2-2.fna.fbcdn.net/v/t1.0-9/61906836_2278152045605831_5300153453316669440_n.jpg?_nc_cat=107&_nc_oc=AQnIbATIEOTGpYEB1iwIWjmOP-LEFKgrFm21ojzX6PKJEgw94VAoBUGTTi82ZVTXA-c&_nc_ht=scontent.frmq2-2.fna&oh=9181b10d999c87bdf4fd9ea211153814&oe=5DCF1536

img3 新增 https://scontent.frmq2-2.fna.fbcdn.net/v/t1.0-9/61657913_2267297493357953_3250269750252535808_n.jpg?_nc_cat=103&_nc_oc=AQnWU5_Qjr4xUafcYKM5kg8shPeNEasu_Ie5BrVRYLcj79b3-M5HaLGJrt5Ht-1Avg0&_nc_ht=scontent.frmq2-2.fna&oh=a2f3b8dacc2640700b164d64b88a38f7&oe=5DD2116D

**Comment by hikarunost** [comment]
shop
id = 59
img1 改為 https://scontent.frmq2-1.fna.fbcdn.net/v/t1.0-9/19511306_1407390212673518_7876573128058356994_n.jpg?_nc_cat=111&_nc_oc=AQnGe8yllnX56y0vWSB-gV6D0OfRQfGxKl0tx10_P1b2uEIeXIjvqClSKcSX06l65yo&_nc_ht=scontent.frmq2-1.fna&oh=c7f617556b4f6eeab64d7c7352c12aed&oe=5DDA47CB

**Comment by hikarunost** [comment]
shop
id = 64
img1 改為 https://scontent.frmq2-2.fna.fbcdn.net/v/t1.0-9/15542304_1821723851439345_321852371529530178_n.jpg?_nc_cat=101&_nc_oc=AQnTC2NI3G3Gc-dlitlPw7XABTy4yrwEnyN5Bk7zIC6DAMGcEReoW9n1I-HYQAv6C5Q&_nc_ht=scontent.frmq2-2.fna&oh=dfc37eb3932c75b7b7aeb3ebebdb951f&oe=5DC99666

**Comment by hikarunost** [comment]
shop
id = 66
img2 改為 https://scontent.frmq2-1.fna.fbcdn.net/v/t1.0-9/67653654_2603526736375164_1939354446278426624_n.jpg?_nc_cat=108&_nc_oc=AQn-spCV3fBLIPoSMbWtSLvHs1MszSBEWAhCABiV4ITlvSQDkNAD4t4XgfDw2wVE2VE&_nc_ht=scontent.frmq2-1.fna&oh=f3885afed72dd03e0dc9ca098b8c7d1a&oe=5DD8D95E

**Comment by hikarunost** [comment]
shop
id = 34
img2 改為 https://cosmosocean.com.tw/upload/index/FB-%E8%BC%AA%E6%92%AD-02_1520652359.jpg

**Comment by hikarunost** [comment]
shop
id = 35 
img3 刪除

**Comment by hikarunost** [comment]
shop
id = 35
img2,3,4 刪除

**Comment by hikarunost** [comment]
shop 
id = 39
img2 改為 https://justwilddivecenter.weebly.com/uploads/1/1/7/3/117353982/27332215-955502637947550-8683707162363326996-n_orig.jpg

**Comment by hikarunost** [comment]
shop
id = 42
img3,4 刪除

**Comment by hikarunost** [comment]
shop
id =35和38是同一家店，不同分店

**Comment by hikarunost** [comment]
早上發現潛點的第一張圖片都變成「/n/n」
已修復此問題

**Comment by hikarunost** [comment]
shop
id = 27
img2 改為 https://scontent.frmq2-1.fna.fbcdn.net/v/t1.0-9/52876819_10156090676200911_1319295734356377600_n.jpg?_nc_cat=106&_nc_oc=AQkTG3K-TZEck79gdEpDbqM3fPr7nLXlX66SutPAiB81Ef0vTXgNxGGvifDI6blfEW4&_nc_ht=scontent.frmq2-1.fna&oh=089ef92b55c848a456e1064437183d6c&oe=5E01CE54

img3 改為 https://scontent.frmq2-1.fna.fbcdn.net/v/t1.0-9/42604152_10155721552660911_1715842802006360064_n.jpg?_nc_cat=111&_nc_oc=AQnneX6P5XxTnbPxiazcw6-YGCqyagTtTgZSRHA2ydki4x2Vh385r5MVBolFeLrUg9w&_nc_ht=scontent.frmq2-1.fna&oh=1a2c30d34297088c9031041873bcd294&oe=5DC8C460

**Comment by ssiyang** [comment]
shop
id = 38 
img2, img3 照片重複

**Comment by hikarunost** [comment]
shop
id = 38
img3 刪除

**Comment by hikarunost** [comment]
@ssiyang 目前發現的錯誤已修正，請再檢查。

雲端表單尚未更新，找時間更新。
