### ISSUE TITLE
API：更新API文件敘述

### ISSUE THREAD

**Issue by anntsai2356** [MonospaceTW/monosparta-diving-server#61]
[API文件](https://divingapi.docs.apiary.io/#)
---
- [x] Show spot search list
- [x] Show spot search with Location and Level
- [x] Show certain spot
- [x] Show spot random list for home
---
- [x] Show shop search list  
- [x] Show shop search with Location and Level
- [x] Show certain shop
- [x] Show shop random list for home
---
- [x] Show article list
- [x] Show article category list
- [x] show certain article detial
- [x] Show article random list for home
---
- [x] Spot/Shop/Article keyword search
---
- [x] Add comment
- [x] Delete comment

**Comment by hikarunost** [comment]
@ssiyang @yinmin8610 @lukechu1997 
我把API文件補齊了，請幫我確認所有API測試的結果是否和example的JSON格式一致，其中一個人有空幫忙看一下，確認沒問題就幫我拉到close，感恩！

請在這裡測試：[API連結](https://divingapi.docs.apiary.io/#)

**Comment by yinmin8610** [comment]
@hikarunost Random Spot回傳有問題

**Comment by anntsai2356** [comment]
@yinmin8610 已修復！！
