### ISSUE TITLE
發表：準備9/5簡報內容

### ISSUE THREAD

**Issue by hikarunost** [MonospaceTW/monosparta-diving-server#73]
9/5發表簡報，可在[雲端連結](https://docs.google.com/presentation/d/1yQalkeqXvGWm3qpS2PwK4ZkuWeBnrA7pJjKG49dkEdQ/edit?usp=sharing)檢視，個人的部分請各自補上。
8/29要跟mentor試報。

*   共同
    *   團隊介紹
*   個人
     *   參加動機
     *   心得 
     *   遭遇困難
     *   未來展望

**Comment by hikarunost** [comment]
我和Alice有更新發表的簡報大綱在notion
[可以點擊這裡查看](https://www.notion.so/monosparta1/f5cf75b2dc4140ce929160a729654081)

成果簡報放在雲端，因為字型問題，就先放PDF參考，關於排版或內容尚有問題的話，也歡迎提出！
[可以點擊這裡查看](https://drive.google.com/file/d/1dFW4WEm755oI5Y-QSuR0UJJaN6gea_xt/view?usp=sharing)

個人分享的部分，就各自準備內容，有需要版面的，請交給我你的簡報內容，麻煩大家了。

講稿的部分我有想了，也會隨時更新在notion，有任何建議也歡迎提出。

**Comment by ssiyang** [comment]
我不用額外的簡報版面

**Comment by hikarunost** [comment]
終於報告完啦！！！！
大家辛苦了
