### ISSUE TITLE
Functional Map：第二版

### ISSUE THREAD

**Issue by anntsai2356** [MonospaceTW/monosparta-diving-server#88]
依照 User Story 歸納出 Functional Map。

**Comment by anntsai2356** [comment]
把 User Story 的需求整理成 Functional Map
已經把所有項目列出來，還沒有全部歸納完
可以在 google 雲端硬碟查看 [Functonal Map_第二版](https://drive.google.com/file/d/1Y-ubtcWi9f9XgamLScDPJsOtJbqXGsFQ/view?usp=sharing)

**Comment by anntsai2356** [comment]
10:20

**Comment by smallkawa** [comment]
0923因為 funtional map 分類方法有誤，今日要重新整理User story後改動funtional map。

時間：

**Comment by smallkawa** [comment]
@bryanpalau @anntsai2356 已幫忙檢查，再交給mentor確認。

時間：0923下午兩點

**Comment by smallkawa** [comment]
0927已完成
