### ISSUE TITLE
取得潛點潛店和潛客的關聯資料（潛點/潛店的評論）

### ISSUE THREAD

**Issue by hikarunost** [MonospaceTW/monosparta-diving-server#9]

**Comment by hikarunost** [comment]
匿名使用者的user_id=1

**Comment by lukechu1997** [comment]
[https://app.zenhub.com/files/196555024/c86a580b-4832-4259-8384-e14ff2b03f64/download](https://app.zenhub.com/files/196555024/c86a580b-4832-4259-8384-e14ff2b03f64/download)
